Repository WildCodeSchool/2022-09-Orleans-CDA-Projet-DevManager, pull requests merged in 2022-12, with the labels that each got.

#20 Feature/init
  .prettierrc
  apps/backend/api/package.json
  apps/frontend/web/package.json
  apps/frontend/web/src/main.tsx
  deployment/docker-compose.dev.yml
  deployment/nginx.dev.conf
  package-lock.json
  package.json
Labels: Sylvain

#23 feat : add page Overview with a picture and a title
  apps/frontend/web/public/overview.jpg
  apps/frontend/web/src/App.tsx
  apps/frontend/web/src/pages/Overview.tsx
Labels: Sylvain

#29 Feature/dockerfiles vps
  .gitignore
  apps/backend/api/Dockerfile
  apps/frontend/web/Dockerfile
  deployment/back.env.sample
  deployment/docker-compose.prod.yml
  deployment/mysql.env.sample
  deployment/nginx.prod.conf
  package.json
Labels: Sylvain

#30 fix: edited dcp down script and nginx conf
  deployment/nginx.prod.conf
  package.json
Labels: Sylvain

#32 setup github actions with dockerhub
  .github/workflows/prod.yml
  .github/workflows/staging.yml
Labels: reviewed, Sylvain

#35 Feature/frontend navbar
  apps/frontend/web/package.json
  apps/frontend/web/src/components/Navbar.tsx
  package-lock.json
  package.json
Labels: reviewed, Sylvain

#27 Feature/register
  .env.sample
  .gitignore
  apps/backend/api/package.json
  apps/backend/api/src/app.module.ts
  apps/backend/api/src/auth/auth.controller.spec.ts
  apps/backend/api/src/auth/auth.controller.ts
  apps/backend/api/src/auth/auth.module.ts
  apps/backend/api/src/auth/auth.service.spec.ts
  apps/backend/api/src/auth/auth.service.ts
  apps/backend/api/src/config/database.config.ts
  apps/backend/api/src/config/migration.config.ts
  apps/backend/api/src/entities/user.entity.ts
  apps/backend/api/src/main.ts
  apps/backend/api/src/users/dto/create-user.dto.ts
  apps/backend/api/src/users/dto/update-user.dto.ts
  apps/backend/api/src/users/users.controller.spec.ts
  apps/backend/api/src/users/users.controller.ts
  apps/backend/api/src/users/users.module.ts
  apps/backend/api/src/users/users.service.spec.ts
  apps/backend/api/src/users/users.service.ts
  apps/frontend/web/package.json
  apps/frontend/web/src/main.tsx
  apps/frontend/web/src/pages/Register.tsx
  libs/typings/src/entities/User.entity.ts
  libs/typings/src/entities/index.ts
  package-lock.json
Labels: reviewed, Sylvain

#38 Feature/frontend web navbar rooms
  apps/frontend/web/package.json
  apps/frontend/web/src/components/NavbarRooms.tsx
  package-lock.json
Labels: reviewed, Sylvain

#33 Features/character
  .gitignore
  apps/backend/api/package.json
  apps/backend/api/src/app.module.ts
  apps/backend/api/src/characters/character.controller.spec.ts
  apps/backend/api/src/characters/character.controller.ts
  apps/backend/api/src/characters/character.module.ts
  apps/backend/api/src/characters/character.service.spec.ts
  apps/backend/api/src/characters/character.service.ts
  apps/backend/api/src/characters/characters/character.entity.spec.ts
  apps/backend/api/src/characters/characters/character.entity.ts
  apps/backend/api/src/config/entities.ts
  apps/backend/api/src/config/migration.config.ts
  apps/backend/api/src/migrations/1670581576397-characters.ts
  apps/frontend/web/src/main.tsx
  package-lock.json
Labels: reviewed, Sylvain

#37 Feature/room
  .gitignore
  apps/backend/api/package.json
  apps/backend/api/src/config/database.config.ts
  apps/backend/api/src/config/entities.ts
  apps/backend/api/src/migration/1671111171342-room.ts
  apps/backend/api/src/rooms/room/room.entity.ts
  apps/backend/api/src/rooms/room/room.spec.ts
  apps/backend/api/src/rooms/rooms.controller.spec.ts
  apps/backend/api/src/rooms/rooms.controller.ts
  apps/backend/api/src/rooms/rooms.module.ts
  apps/backend/api/src/rooms/rooms.service.spec.ts
  apps/backend/api/src/rooms/rooms.service.ts
Labels: Sylvain

#39 Feature/acheter un personnage
  .gitignore
  apps/frontend/web/src/components/CharacterCard.tsx
  apps/frontend/web/src/main.tsx
Labels: review needed

#40 Feature/new game
  .env.sample
  apps/backend/api/package.json
  apps/backend/api/src/app.module.ts
  apps/backend/api/src/auth/auth.controller.ts
  apps/backend/api/src/auth/auth.module.ts
  apps/backend/api/src/auth/auth.service.ts
  apps/backend/api/src/characters/entities/character.entity.spec.ts
  apps/backend/api/src/characters/entities/character.entity.ts
  apps/backend/api/src/config/database.config.ts
  apps/backend/api/src/config/entities.ts
  apps/backend/api/src/games/dto/create-game.dto.ts
  apps/backend/api/src/games/dto/update-game.dto.ts
  apps/backend/api/src/games/entities/game.entity.ts
  apps/backend/api/src/games/games.controller.spec.ts
  apps/backend/api/src/games/games.controller.ts
  apps/backend/api/src/games/games.module.ts
  apps/backend/api/src/games/games.service.spec.ts
  apps/backend/api/src/games/games.service.ts
  apps/backend/api/src/migrations/1670495709446-game.d.ts
  apps/backend/api/src/migrations/1670495709446-game.js
  apps/backend/api/src/migrations/1670495709446-game.js.map
  apps/backend/api/src/migrations/1670495709446-game.ts
  apps/backend/api/src/migrations/1671111171342-room.ts
  apps/backend/api/src/users/entities/user.entity.ts
  apps/backend/api/src/users/users.module.ts
  apps/backend/api/src/users/users.service.ts
  apps/backend/api/tsconfig.build.tsbuildinfo
  apps/frontend/web/src/App.tsx
  apps/frontend/web/src/components/CompanyImageRadioCard.tsx
  apps/frontend/web/src/components/ModalCompanyImage.tsx
  apps/frontend/web/src/main.tsx
  apps/frontend/web/src/pages/NewGame.tsx
  libs/typings/src/index.ts
  package-lock.json
Labels: Sylvain

#58 fix(backend/api): delete db config file, delete useless migrations fi…
  apps/backend/api/src/app/app.controller.spec.ts
  apps/backend/api/src/app/app.controller.ts
  apps/backend/api/src/app/app.module.ts
  apps/backend/api/src/app/app.service.ts
  apps/backend/api/src/app/auth/auth.controller.spec.ts
  apps/backend/api/src/app/auth/auth.controller.ts
  apps/backend/api/src/app/auth/auth.module.ts
  apps/backend/api/src/app/auth/auth.service.spec.ts
  apps/backend/api/src/app/auth/auth.service.ts
  apps/backend/api/src/app/characters/character.controller.spec.ts
  apps/backend/api/src/app/characters/character.controller.ts
  apps/backend/api/src/app/characters/character.module.ts
  apps/backend/api/src/app/characters/character.service.spec.ts
  apps/backend/api/src/app/characters/character.service.ts
  apps/backend/api/src/app/characters/entities/character.entity.spec.ts
  apps/backend/api/src/app/characters/entities/character.entity.ts
  apps/backend/api/src/app/games/dto/create-game.dto.ts
  apps/backend/api/src/app/games/dto/update-game.dto.ts
  apps/backend/api/src/app/games/entities/game.entity.ts
  apps/backend/api/src/app/games/games.controller.spec.ts
  apps/backend/api/src/app/games/games.controller.ts
  apps/backend/api/src/app/games/games.module.ts
  apps/backend/api/src/app/games/games.service.spec.ts
  apps/backend/api/src/app/games/games.service.ts
  apps/backend/api/src/app/rooms/entities/room.entity.ts
  apps/backend/api/src/app/rooms/entities/room.spec.ts
  apps/backend/api/src/app/rooms/rooms.controller.spec.ts
  apps/backend/api/src/app/rooms/rooms.controller.ts
  apps/backend/api/src/app/rooms/rooms.module.ts
  apps/backend/api/src/app/rooms/rooms.service.spec.ts
  apps/backend/api/src/app/rooms/rooms.service.ts
  apps/backend/api/src/app/users/dto/create-user.dto.ts
  apps/backend/api/src/app/users/dto/update-user.dto.ts
  apps/backend/api/src/app/users/entities/user.entity.ts
  apps/backend/api/src/app/users/users.controller.spec.ts
  apps/backend/api/src/app/users/users.controller.ts
  apps/backend/api/src/app/users/users.module.ts
  apps/backend/api/src/app/users/users.service.spec.ts
  apps/backend/api/src/app/users/users.service.ts
  apps/backend/api/src/config/database.config.ts
  apps/backend/api/src/config/entities.ts
  apps/backend/api/src/main.ts
  apps/backend/api/src/migrations/1670495709446-game.d.ts
  apps/backend/api/src/migrations/1670495709446-game.js
  apps/backend/api/src/migrations/1670495709446-game.js.map
Labels: reviewed, Sylvain

#59 feat(frontend/web): configure routes, add pages files, delete empty a…
  apps/frontend/web/src/App.tsx
  apps/frontend/web/src/assets/.gitkeep
  apps/frontend/web/src/pages/About.tsx
  apps/frontend/web/src/pages/AccountSettings.tsx
  apps/frontend/web/src/pages/Assistance.tsx
  apps/frontend/web/src/pages/GameSettings.tsx
  apps/frontend/web/src/pages/Home.tsx
  apps/frontend/web/src/pages/Login.tsx
  apps/frontend/web/src/pages/Overview.tsx
  apps/frontend/web/src/pages/Page404.tsx
  apps/frontend/web/src/pages/Room.tsx
Labels: reviewed, Sylvain

#60 feat(frontend/web): redesign the style, fix the modal opening
  apps/frontend/web/src/components/ModalCompanyImage.tsx
  apps/frontend/web/src/pages/NewGame.tsx
Labels: reviewed, Sylvain

#62 feat(backend/api): generate latest migrations
  apps/backend/api/src/migrations/1671615134513-user.ts
Labels: reviewed, Sylvain

#63 feat(backend/api): edit synchronize migrations to true
  apps/backend/api/src/app/app.module.ts
  apps/backend/api/src/config/migration.config.ts
  apps/backend/api/src/migrations/.gitkeep
  apps/backend/api/src/migrations/1670495709446-game.ts
  apps/backend/api/src/migrations/1670581576397-characters.ts
  apps/backend/api/src/migrations/1671111171342-room.ts
  apps/backend/api/src/migrations/1671615134513-user.ts
Labels: reviewed, Sylvain
