Repository WildCodeSchool/2022-09-Orleans-CDA-Projet-DevManager, pull requests merged in 2023-02, with the labels that each got.

#98 feat: admin interface using refine
  apps/frontend/admin/.gitignore
  apps/frontend/admin/.npmrc
  apps/frontend/admin/README.MD
  apps/frontend/admin/package-lock.json
  apps/frontend/admin/package.json
  apps/frontend/admin/public/favicon.ico
  apps/frontend/admin/public/index.html
  apps/frontend/admin/src/App.tsx
  apps/frontend/admin/src/index.tsx
  apps/frontend/admin/src/meta.json
  apps/frontend/admin/src/react-app-env.d.ts
  apps/frontend/admin/src/reportWebVitals.ts
  apps/frontend/admin/src/setupTests.ts
  apps/frontend/admin/tsconfig.json
  deployment/nginx.dev.conf
  package-lock.json
Labels: reviewed, Sylvain

#104 feature/front account settings
  apps/frontend/web/src/App.tsx
  apps/frontend/web/src/components/Protected.tsx
  apps/frontend/web/src/components/UserContactFiller.tsx
  apps/frontend/web/src/components/UserImageFiller.tsx
  apps/frontend/web/src/components/UserPasswordFiller.tsx
  apps/frontend/web/src/components/popups/SlideUpModal.tsx
  apps/frontend/web/src/contexts/AuthContext.tsx
  apps/frontend/web/src/pages/AccountSettings.tsx
Labels: reviewed, Sylvain

#116 feat: add docker reset script
  package.json
Labels: reviewed, Sylvain

#117 Feature/forge scripts
  apps/tools/forge/index.js
  apps/tools/forge/package.json
  deployment/sql/01.sql
  package-lock.json
  package.json
Labels: reviewed, Sylvain

#118 feat: add script to reset node_modules
  package.json
Labels: reviewed, Sylvain

#108 feat:can now delete game or user
  apps/backend/api/src/app/games/games.service.ts
  apps/backend/api/src/app/users/users.service.ts
  apps/backend/api/src/entities/game.entity.ts
  apps/backend/api/src/entities/user.entity.ts
  apps/frontend/web/src/pages/AccountSettings.tsx
  apps/frontend/web/src/pages/GameSettings.tsx
Labels: reviewed, Sylvain

#113 Feature/get images from db for forms
  apps/frontend/web/src/components/CompanyImageFiller.tsx
  apps/frontend/web/src/components/GameImageFiller.tsx
  apps/frontend/web/src/components/RadioCard.tsx
  apps/frontend/web/src/components/UserImageFiller.tsx
  apps/frontend/web/src/pages/GameSettings.tsx
  apps/frontend/web/src/pages/NewGame.tsx
  apps/frontend/web/src/utils/fetchImage.ts
Labels: reviewed, Sylvain

#122 Feature/link to admin
  apps/frontend/admin/src/App.tsx
  apps/frontend/web/src/App.tsx
  apps/frontend/web/src/pages/About.tsx
  deployment/nginx.dev.conf
Labels: reviewed, Sylvain

#112 feat: procedure sql
  deployment/sql/02.sql
Labels: reviewed, Sylvain

#124 feat(frontend/web): add id attribute to inputs in login
  apps/frontend/web/src/pages/Login.tsx
Labels: reviewed, Sylvain

#115 style(frontend web): add responsive to account settings, assistance a…
  apps/frontend/web/src/pages/AccountSettings.tsx
  apps/frontend/web/src/pages/Assistance.tsx
  apps/frontend/web/src/pages/GameSettings.tsx
  apps/frontend/web/src/pages/NewGame.tsx
Labels: reviewed, Sylvain

#120 feat: resolve issue with setIsLoadingUser
  apps/backend/api/src/app/auth/auth.controller.ts
  apps/frontend/web/src/App.tsx
  apps/frontend/web/src/components/Navbar.tsx
  apps/frontend/web/src/components/Protected.tsx
  apps/frontend/web/src/contexts/AuthContext.tsx
Labels: reviewed, Sylvain

#123 feat(frontend/web): remove all console.log
  apps/frontend/web/src/components/CharacterCard.tsx
  apps/frontend/web/src/components/EventCard.tsx
  apps/frontend/web/src/pages/Room.tsx
Labels: reviewed, Sylvain

#125 feat(frontend/web): handle press enter to submit form
  apps/frontend/web/src/pages/Login.tsx
Labels: reviewed, Sylvain

#126 feat: add bonus in procedure
  deployment/sql/02.sql
Labels: reviewed, Sylvain

#127 fix: udpate forge with company and profile images, modify color modal…
  apps/backend/api/src/app/forge/forge.service.ts
  apps/frontend/web/src/pages/AccountSettings.tsx
  apps/frontend/web/src/pages/Assistance.tsx
  apps/frontend/web/src/pages/GameSettings.tsx
Labels: reviewed, Sylvain

#129 feat: restyle of page home
  apps/frontend/web/public/developer-splash.png
  apps/frontend/web/src/pages/Home.tsx
Labels: reviewed, Sylvain

#130 feat: link about work
  apps/frontend/web/src/App.tsx
Labels: reviewed, Sylvain

#132 feat: add column point remove ceo name
  apps/frontend/web/src/pages/Leaderboard.tsx
Labels: changes requested

#133 Feature/logic game
  apps/backend/api/src/app/forge/forge.service.ts
  apps/backend/api/src/app/game-characters/game-characters.controller.ts
  apps/backend/api/src/app/game-characters/game-characters.service.ts
  apps/backend/api/src/app/game-events/game-events.controller.ts
  apps/backend/api/src/app/game-events/game-events.service.ts
  apps/backend/api/src/app/game-resources/game-resources.controller.ts
  apps/backend/api/src/app/game-resources/game-resources.service.ts
  apps/backend/api/src/app/game-rooms/game-rooms.controller.ts
  apps/backend/api/src/app/game-rooms/game-rooms.service.ts
  apps/backend/api/src/app/games/games.controller.ts
  apps/backend/api/src/app/games/games.service.ts
  apps/frontend/web/src/App.tsx
  apps/frontend/web/src/components/CharacterCard.tsx
  apps/frontend/web/src/components/EventCard.tsx
  apps/frontend/web/src/components/NavbarRooms.tsx
  apps/frontend/web/src/components/popups/EventModal.tsx
  apps/frontend/web/src/pages/Room.tsx
Labels: reviewed

#135 fix: change the update and refactor the cursor
  deployment/sql/02.sql
Labels: reviewed, Sylvain

#137 fix: change name of table
  deployment/sql/02.sql
Labels: reviewed, Sylvain

#131 feat: refactor forge service
  apps/backend/api/src/app/forge/forge.service.ts
  apps/backend/api/src/app/games/dto/create-game.dto.ts
  apps/backend/api/src/app/games/games.module.ts
  apps/backend/api/src/app/games/games.service.ts
  apps/backend/api/src/app/images/dto/create-image.dto.ts
  apps/backend/api/src/app/images/images.controller.ts
  apps/backend/api/src/app/images/images.service.ts
  apps/backend/api/src/app/users/users.controller.ts
  apps/backend/api/src/app/users/users.service.ts
  apps/backend/api/src/entities/image.entity.ts
  apps/frontend/web/src/components/DeleteAccountFiller.tsx
  apps/frontend/web/src/components/GameDetailsFiller.tsx
  apps/frontend/web/src/components/GameImageFiller.tsx
  apps/frontend/web/src/components/RadioCard.tsx
  apps/frontend/web/src/components/ResetGameFiller.tsx
  apps/frontend/web/src/components/UserContactFiller.tsx
  apps/frontend/web/src/components/UserImageFiller.tsx
  apps/frontend/web/src/components/UserPasswordFiller.tsx
  apps/frontend/web/src/components/popups/SlideUpModal.tsx
  apps/frontend/web/src/pages/AccountSettings.tsx
  apps/frontend/web/src/pages/GameSettings.tsx
  apps/frontend/web/src/pages/NewGame.tsx
  libs/typings/src/types/DeepPartial.ts
  libs/typings/src/types/index.ts
Labels: reviewed, Sylvain

#142 fix:change order link navbar and scrool in overview and assistance
  apps/frontend/web/src/components/Navbar.tsx
  apps/frontend/web/src/components/ResourcesBar.tsx
  apps/frontend/web/src/pages/Assistance.tsx
  apps/frontend/web/src/pages/Overview.tsx
Labels: reviewed, Sylvain

#143 feat(frontend/web): add inner shadows to navbars
  apps/frontend/web/src/components/Navbar.tsx
  apps/frontend/web/src/components/NavbarRooms.tsx
Labels: reviewed, Sylvain

#141 Feature/add characters
  apps/backend/api/src/app/forge/forge.service.ts
  apps/backend/api/src/app/game-characters/dto/add-game-character.dto.ts
  apps/backend/api/src/app/game-characters/game-characters.controller.ts
  apps/backend/api/src/app/game-characters/game-characters.module.ts
  apps/backend/api/src/app/game-characters/game-characters.service.ts
  apps/frontend/web/src/components/CharacterCard.tsx
  apps/frontend/web/src/components/ResourcesBar.tsx
  apps/frontend/web/src/pages/Room.tsx
Labels: reviewed, Sylvain

#140 Feature/redirect andblock access to new game
  apps/backend/api/src/app/games/games.controller.ts
  apps/backend/api/src/app/games/games.service.ts
  apps/frontend/web/src/components/Protected.tsx
  apps/frontend/web/src/components/VerifyGame.tsx
Labels: reviewed, Sylvain

#145 Feature/modify style resource bar
  apps/frontend/web/src/components/ResourcesBar.tsx
  apps/frontend/web/src/pages/Room.tsx
Labels: reviewed, Sylvain

#147 fix: order
  apps/frontend/web/src/components/DrawerNavbar.tsx
Labels: reviewed, Sylvain

#144 feat: add order column to database, add 4 more user data in forge
  apps/backend/api/src/app/forge/forge.service.ts
  apps/backend/api/src/app/game-characters/game-characters.service.ts
  apps/backend/api/src/app/game-events/game-events.service.ts
  apps/backend/api/src/app/game-resources/game-resources.service.ts
  apps/backend/api/src/app/game-rooms/game-rooms.service.ts
  apps/backend/api/src/entities/character.entity.ts
  apps/backend/api/src/entities/event.entity.ts
  apps/backend/api/src/entities/resource.entity.ts
  apps/backend/api/src/entities/room.entity.ts
  apps/frontend/web/src/components/NavbarRooms.tsx
  apps/frontend/web/src/components/ResourcesBar.tsx
Labels: reviewed, Sylvain

#150 feat:clear cookie in logout and remove fetch game cookie in useEffect…
  apps/backend/api/src/app/auth/auth.controller.ts
  apps/frontend/web/src/App.tsx
Labels: reviewed, Sylvain

#152 feat: resposive resource bar and charch card
  apps/frontend/web/src/components/DrawerResources.tsx
  apps/frontend/web/src/components/ResourcesBar.tsx
  apps/frontend/web/src/pages/Room.tsx
Labels: reviewed, Sylvain

#153 feat: remove link
  apps/frontend/web/src/pages/About.tsx
Labels: reviewed, Sylvain

#149 Feature/data
  apps/backend/api/src/app/game-characters/game-characters.service.ts
  apps/backend/api/src/app/game-events/game-events.service.ts
  apps/backend/api/src/app/game-resources/game-resources.controller.ts
  apps/backend/api/src/app/game-resources/game-resources.service.ts
  apps/backend/api/src/app/game-rooms/dto/update-total-size-game-room.dto.ts
  apps/backend/api/src/app/game-rooms/game-rooms.controller.ts
  apps/backend/api/src/app/game-rooms/game-rooms.module.ts
  apps/backend/api/src/app/game-rooms/game-rooms.service.ts
  apps/frontend/web/src/components/CharacterCard.tsx
  apps/frontend/web/src/components/EventCard.tsx
  apps/frontend/web/src/components/MoreAreaCard.tsx
  apps/frontend/web/src/components/Navbar.tsx
  apps/frontend/web/src/components/NavbarRooms.tsx
  apps/frontend/web/src/components/ResourcesBar.tsx
  apps/frontend/web/src/components/popups/CharacterModal.tsx
  apps/frontend/web/src/components/popups/DrawerNavbar.tsx
  apps/frontend/web/src/components/popups/DrawerResources.tsx
  apps/frontend/web/src/components/popups/EventModal.tsx
  apps/frontend/web/src/components/popups/ModalResources.tsx
  apps/frontend/web/src/contexts/GameContext.tsx
  apps/frontend/web/src/main.tsx
  apps/frontend/web/src/pages/Room.tsx
Labels: reviewed, Sylvain

#158 feat: background for modal charac
  apps/frontend/web/src/components/popups/CharacterModal.tsx
Labels: reviewed, Sylvain

#155 feat(frontend/web): add image of mayor, restylize the front
  apps/frontend/web/public/mayor.svg
  apps/frontend/web/src/pages/Overview.tsx
Labels: reviewed, Sylvain

#157 feat: add password change in settings
  apps/frontend/web/src/components/UserPasswordFiller.tsx
Labels: reviewed, Sylvain

#161 fix: modify method findAllWithResourcesUsedAndProduced in GameResourc…
  apps/backend/api/src/app/game-resources/game-resources.service.ts
  apps/frontend/web/src/components/ResourcesBar.tsx
  apps/frontend/web/src/components/popups/ModalResources.tsx
Labels: reviewed, Sylvain

#162 feat: fix typo and bug more area
  apps/frontend/web/src/components/MoreAreaCard.tsx
Labels: reviewed, Sylvain

#159 Feature/start game db
  apps/backend/api/src/app/games/games.controller.ts
  apps/backend/api/src/app/games/games.module.ts
  apps/backend/api/src/app/games/games.service.ts
  apps/frontend/web/src/components/VerifyGame.tsx
  apps/frontend/web/src/contexts/GameContext.tsx
  apps/frontend/web/src/pages/NewGame.tsx
Labels: reviewed, Sylvain

#160 feature/ preparation release
  deployment/docker-compose.prod.yml
Labels: reviewed, Sylvain

#156 Feature/size rooms price character
  apps/backend/api/src/app/game-characters/game-characters.service.ts
  apps/frontend/web/src/components/ResourcesBar.tsx
Labels: reviewed, Sylvain

#164 feat: add image devdollar and remove fake rank
  apps/frontend/web/src/pages/Leaderboard.tsx
Labels: reviewed, Sylvain

#166 Feature/rooms style
  apps/backend/api/src/app/games/games.service.ts
  apps/frontend/web/public/placeholder.png
  apps/frontend/web/src/App.tsx
  apps/frontend/web/src/components/CharacterCard.tsx
  apps/frontend/web/src/components/EventCard.tsx
  apps/frontend/web/src/components/MobileNavbar.tsx
  apps/frontend/web/src/components/MobileNavbarRooms.tsx
  apps/frontend/web/src/components/MoreAreaCard.tsx
  apps/frontend/web/src/components/Navbar.tsx
  apps/frontend/web/src/components/NavbarRooms.tsx
  apps/frontend/web/src/components/NavbarTab.tsx
  apps/frontend/web/src/components/ResourcesBar.tsx
  apps/frontend/web/src/components/RoomElementCard.tsx
  apps/frontend/web/src/components/popups/CharacterModal.tsx
  apps/frontend/web/src/components/popups/EventModal.tsx
  apps/frontend/web/src/pages/GameSettings.tsx
  apps/frontend/web/src/pages/Room.tsx
Labels: reviewed, Sylvain

#167 feat: change Partial to Deep
  apps/frontend/web/src/components/UserContactFiller.tsx
  apps/frontend/web/src/components/UserImageFiller.tsx
  apps/frontend/web/src/components/UserPasswordFiller.tsx
  apps/frontend/web/src/pages/AccountSettings.tsx
Labels: reviewed, Sylvain

#170 feat:remove navbar in page
  apps/frontend/web/src/pages/About.tsx
  apps/frontend/web/src/pages/AccountSettings.tsx
  apps/frontend/web/src/pages/Assistance.tsx
  apps/frontend/web/src/pages/Leaderboard.tsx
  apps/frontend/web/src/pages/Overview.tsx
Labels: reviewed, Sylvain

#171 feat: take the check logic and style
  apps/backend/api/src/app/forge/forge.service.ts
  apps/backend/api/src/app/game-rooms/game-rooms.controller.ts
  apps/backend/api/src/app/game-rooms/game-rooms.service.ts
  apps/backend/api/src/app/games/games.controller.ts
  apps/backend/api/src/app/games/games.service.ts
  apps/frontend/web/public/lock.svg
  apps/frontend/web/src/components/ResourcesBar.tsx
  apps/frontend/web/src/components/RoomElementCard.tsx
  apps/frontend/web/src/pages/Overview.tsx
  apps/frontend/web/src/pages/Room.tsx
Labels: reviewed, Sylvain

#173 feat: create forge for prod
  apps/backend/api/src/app/app.module.ts
  apps/backend/api/src/app/forge-prod/forge-prod.controller.ts
  apps/backend/api/src/app/forge-prod/forge-prod.module.ts
  apps/backend/api/src/app/forge-prod/forge-prod.service.ts
  package.json
Labels: reviewed, Sylvain

#172 Feat(frontend web): add ModalResources
  apps/frontend/web/src/components/ResourcesBar.tsx
  apps/frontend/web/src/components/popups/DrawerResources.tsx
  apps/frontend/web/src/pages/Room.tsx
Labels: reviewed, Sylvain

#176 feat: resolve issues with detail character and event modal
  apps/frontend/web/src/components/RoomElementCard.tsx
Labels: reviewed, Sylvain

#177 Release/0.1.0
  .env.sample
  apps/backend/api/src/app/app.controller.ts
  apps/backend/api/src/app/app.module.ts
  apps/backend/api/src/app/app.service.ts
  apps/backend/api/src/app/bonus-malus/bonus-malus.controller.ts
  apps/backend/api/src/app/characters/character.controller.ts
  apps/backend/api/src/app/events/dto/create-event.dto.ts
  apps/backend/api/src/app/events/events.controller.ts
  apps/backend/api/src/app/game-events/game-events.controller.ts
  apps/backend/api/src/app/game-resources/game-resources.controller.ts
  apps/backend/api/src/app/game-rooms/game-rooms.controller.ts
  apps/backend/api/src/app/games/dto/create-game.dto.ts
  apps/backend/api/src/app/games/games.controller.ts
  apps/backend/api/src/app/images/images.controller.ts
  apps/backend/api/src/app/resources-produced/resources-produced.controller.ts
  apps/backend/api/src/app/resources-used/resources-used.controller.ts
  apps/backend/api/src/app/resources/dto/create-resource.dto.ts
  apps/backend/api/src/app/resources/resources.controller.ts
  apps/backend/api/src/app/resources/resources.service.ts
  apps/backend/api/src/app/rooms/rooms.controller.ts
  apps/backend/api/src/app/users/dto/create-user.dto.ts
  apps/backend/api/src/app/users/dto/login-user.dto.ts
  apps/backend/api/src/app/users/dto/register-user.dto.ts
  apps/backend/api/src/app/users/users.controller.ts
  apps/backend/api/src/config/migration.config.ts
  apps/backend/api/src/entities/bonus-malus.entity.ts
  apps/backend/api/src/entities/character.entity.ts
  apps/backend/api/src/entities/event.entity.ts
  apps/backend/api/src/migrations/1676640285461-migration-release.ts
  apps/frontend/mobile/src/App.tsx
  apps/frontend/mobile/src/screens/OverviewScreen.tsx
  apps/frontend/mobile/src/screens/RegisterScreen.tsx
  apps/frontend/web/src/App.tsx
  apps/frontend/web/src/components/ResetGameFiller.tsx
  apps/frontend/web/src/components/UserContactFiller.tsx
  apps/frontend/web/src/components/UserImageFiller.tsx
  apps/frontend/web/src/components/UserPasswordFiller.tsx
  apps/frontend/web/src/pages/About.tsx
  apps/frontend/web/src/pages/AccountSettings.tsx
  apps/frontend/web/src/pages/GameSettings.tsx
  apps/frontend/web/src/pages/Home.tsx
  apps/frontend/web/src/pages/NewGame.tsx
  apps/frontend/web/src/pages/Page404.tsx
  libs/typings/src/entities/User.entity.ts
  libs/typings/src/entities/index.ts
  libs/typings/src/index.ts
  libs/typings/src/interfaces/index.ts
  libs/typings/src/types/index.ts
Labels: reviewed, Sylvain

#178 feat: add margin left to all pages
  apps/frontend/web/src/pages/About.tsx
  apps/frontend/web/src/pages/AccountSettings.tsx
  apps/frontend/web/src/pages/Assistance.tsx
  apps/frontend/web/src/pages/GameSettings.tsx
  apps/frontend/web/src/pages/Leaderboard.tsx
Labels: reviewed, Sylvain

#175 feat:close the last toast
  apps/frontend/web/src/components/RoomElementCard.tsx
Labels: reviewed, Sylvain

#179 feat: add flexbox to center elements
  apps/frontend/web/src/components/GameImageFiller.tsx
  apps/frontend/web/src/components/RadioCard.tsx
  apps/frontend/web/src/components/UserImageFiller.tsx
Labels: reviewed, Sylvain

#181 Release/0.1.1
  apps/backend/api/src/app/app.module.ts
  apps/backend/api/src/app/forge-prod/forge-prod.controller.ts
  apps/backend/api/src/app/forge-prod/forge-prod.module.ts
  apps/backend/api/src/app/forge-prod/forge-prod.service.ts
  apps/backend/api/src/app/forge/forge.service.ts
  apps/backend/api/src/app/game-characters/game-characters.service.ts
  apps/backend/api/src/app/game-resources/game-resources.service.ts
  apps/backend/api/src/app/games/games.controller.ts
  apps/backend/api/src/app/games/games.module.ts
  apps/backend/api/src/app/games/games.service.ts
  apps/frontend/web/public/lock.svg
  apps/frontend/web/public/mayor.svg
  apps/frontend/web/public/placeholder.png
  apps/frontend/web/src/App.tsx
  apps/frontend/web/src/components/CharacterCard.tsx
  apps/frontend/web/src/components/EventCard.tsx
  apps/frontend/web/src/components/GameImageFiller.tsx
  apps/frontend/web/src/components/MobileNavbar.tsx
  apps/frontend/web/src/components/MobileNavbarRooms.tsx
  apps/frontend/web/src/components/MoreAreaCard.tsx
  apps/frontend/web/src/components/Navbar.tsx
  apps/frontend/web/src/components/NavbarRooms.tsx
  apps/frontend/web/src/components/NavbarTab.tsx
  apps/frontend/web/src/components/RadioCard.tsx
  apps/frontend/web/src/components/ResourcesBar.tsx
  apps/frontend/web/src/components/RoomElementCard.tsx
  apps/frontend/web/src/components/UserImageFiller.tsx
  apps/frontend/web/src/components/UserPasswordFiller.tsx
  apps/frontend/web/src/components/VerifyGame.tsx
  apps/frontend/web/src/components/popups/CharacterModal.tsx
  apps/frontend/web/src/components/popups/DrawerResources.tsx
  apps/frontend/web/src/components/popups/EventModal.tsx
  apps/frontend/web/src/components/popups/ModalResources.tsx
  apps/frontend/web/src/contexts/GameContext.tsx
  apps/frontend/web/src/pages/About.tsx
  apps/frontend/web/src/pages/AccountSettings.tsx
  apps/frontend/web/src/pages/Assistance.tsx
  apps/frontend/web/src/pages/GameSettings.tsx
  apps/frontend/web/src/pages/Leaderboard.tsx
  apps/frontend/web/src/pages/NewGame.tsx
  apps/frontend/web/src/pages/Overview.tsx
  apps/frontend/web/src/pages/Room.tsx
  deployment/docker-compose.prod.yml
  package.json
Labels: reviewed, Sylvain

#183 feat(backend/api): change length of label column
  apps/backend/api/src/entities/bonus-malus.entity.ts
  apps/backend/api/src/entities/event.entity.ts
Labels: reviewed, Sylvain

#184 feat(backend/api): rename energic drinks to energy drinks
  apps/backend/api/src/app/forge-prod/forge-prod.service.ts
  apps/backend/api/src/app/forge/forge.service.ts
Labels: reviewed, Sylvain

#185 feat:devdollar in leaderboard
  apps/backend/api/src/app/game-resources/game-resources.service.ts
  apps/frontend/web/src/pages/Leaderboard.tsx
Labels: reviewed, Sylvain

#169 feat: add images for the 2d and create the baase of the rooms
  apps/frontend/web/package.json
  apps/frontend/web/public/billard.png
  apps/frontend/web/public/carpet.png
  apps/frontend/web/public/chocolate.png
  apps/frontend/web/public/desk-no-bg.png
  apps/frontend/web/public/desk.png
  apps/frontend/web/public/drink.png
  apps/frontend/web/public/dual_screen.png
  apps/frontend/web/public/lunch.png
  apps/frontend/web/public/news.png
  apps/frontend/web/public/soccer.png
  apps/frontend/web/public/sofa.png
  apps/frontend/web/public/zen_desk.png
  apps/frontend/web/src/components/BreakRoom2D.tsx
  apps/frontend/web/src/components/GameFrame.tsx
  apps/frontend/web/src/components/MovingSprite.tsx
  apps/frontend/web/src/components/Offices2D.tsx
  apps/frontend/web/src/components/OpenSpace2D.tsx
  apps/frontend/web/src/pages/Room.tsx
  package-lock.json
Labels: reviewed, Sylvain

#186 feat(backend/api): add characters and events details for the modal
  apps/backend/api/src/app/forge-prod/forge-prod.service.ts
  apps/backend/api/src/app/forge/forge.controller.spec.ts
  apps/backend/api/src/app/forge/forge.service.spec.ts
  apps/backend/api/src/app/forge/forge.service.ts
Labels: reviewed, Sylvain

#187 Release/0.1.2
  apps/backend/api/src/app/forge-prod/forge-prod.service.ts
  apps/backend/api/src/app/forge/forge.controller.spec.ts
  apps/backend/api/src/app/forge/forge.service.spec.ts
  apps/backend/api/src/app/forge/forge.service.ts
  apps/backend/api/src/app/game-resources/game-resources.service.ts
  apps/backend/api/src/entities/bonus-malus.entity.ts
  apps/backend/api/src/entities/event.entity.ts
  apps/backend/api/src/migrations/1677057380274-r012.ts
  apps/frontend/web/package.json
  apps/frontend/web/public/billard.png
  apps/frontend/web/public/carpet.png
  apps/frontend/web/public/chocolate.png
  apps/frontend/web/public/desk-no-bg.png
  apps/frontend/web/public/desk.png
  apps/frontend/web/public/drink.png
  apps/frontend/web/public/dual_screen.png
  apps/frontend/web/public/lunch.png
  apps/frontend/web/public/news.png
  apps/frontend/web/public/soccer.png
  apps/frontend/web/public/sofa.png
  apps/frontend/web/public/zen_desk.png
  apps/frontend/web/src/components/BreakRoom2D.tsx
  apps/frontend/web/src/components/GameFrame.tsx
  apps/frontend/web/src/components/MovingSprite.tsx
  apps/frontend/web/src/components/Offices2D.tsx
  apps/frontend/web/src/components/OpenSpace2D.tsx
  apps/frontend/web/src/pages/Leaderboard.tsx
  apps/frontend/web/src/pages/Room.tsx
  package-lock.json
Labels: reviewed, Sylvain

#188 Release/0.1.2
  apps/backend/api/src/migrations/1677057380274-r012.ts
  apps/frontend/web/src/pages/Leaderboard.tsx
  package-lock.json
Labels: reviewed, Sylvain
